services:
  afrisinc-pay:
    build: .
    container_name: afrisinc_pay
    restart: unless-stopped
    ports:
      - "3400:3400"
    env_file:
      - .env
    networks:
      - afrisinc_net

networks:
  afrisinc_net:
    external: true
